artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/RaflyQowi/Project_Dataset/raw/main/loan%20status%20data/loan%20classification.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts\data_ingestion\credit_train.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/credit_train.csv

model_trainer:
  root_dir: artifacts\model_trainer
  train_data_path: artifacts\data_transformation\train.csv
  test_data_path: artifacts\data_transformation\test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts\model_evaluation
  test_data_path: artifacts\data_transformation\test.csv
  model_path: artifacts\model_trainer\model.joblib
  metric_file_path: artifacts\model_evaluation\metrics.json
