name: Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/end-to-end-loan-status-classification:tagname .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/end-to-end-loan-status-classification:tagname
